In [17]:
import numpy as np
import pymysql
import pandas as pd

from tqdm import tqdm

In [18]:
# 2단계 : connect(mysql 접속)
host_url = 'rowan-test-db.c2rbzfa0saqk.ap-northeast-2.rds.amazonaws.com'
db = pymysql.connect(host=host_url, port=4406, user='root', passwd='rowan08101!', db='sb_db', charset='utf8')
# 3단계 : cusor : 커서 생성
cursor = db.cursor()

In [19]:
# 4단계 : sql문 작성(데이터 read)
query = "SELECT gl.*, ur.*, o.organization_idx FROM sb_db.brain_game_log gl LEFT JOIN sb_db.map_assignment_unit_user mauu ON gl.assignment_unit_user = mauu.assignment_unit_user_idx JOIN sb_db.user_real ur ON mauu.user = ur.idx JOIN brain_organization  o ON ur.organization = o.organization_name"
# 5단계 : pd로 sql문 실행
game_log = pd.read_sql(query, db)

C:\Users\sanghyun\Anaconda3\envs\sb-db\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

In [20]:
cursor.close()
db.close()

In [21]:
# game_log = pd.read_csv('brain_game_log_v2.csv')

In [22]:
game_log.set_index('game_log_idx', inplace=True)

In [23]:
game_log

,create_time,game_log_next_level,game_log_level,game_log_limit,game_log_record,game_log_score,game_log_success,assignment_unit_user,idx,userId,birth,gender,education,height,job,name,organization,organization_idx
game_log_idx,,,,,,,,,,,,,,,,,,
721,2021-05-11 10:31:00,4,4,300,"[{""correct"":1,""speed"":286.9}]",100.0,100.00,1045,39,A0001,19520219,M,16,172,,소필영,로아신경과의원,4
749,2021-05-12 15:10:00,3,3,180,"[{""correct"":1,""speed"":25.2},{""correct"":1,""spee...",2000.0,95.24,1046,39,A0001,19520219,M,16,172,,소필영,로아신경과의원,4
768,2021-05-13 08:22:00,3,3,180,"[{""correct"":1,""speed"":5.8},{""correct"":1,""speed...",2300.0,95.83,1046,39,A0001,19520219,M,16,172,,소필영,로아신경과의원,4
718,2021-05-11 10:15:00,3,3,180,"[{""correct"":1,""speed"":44.7},{""correct"":1,""spee...",400.0,100.00,1048,39,A0001,19520219,M,16,172,,소필영,로아신경과의원,4
719,2021-05-11 10:19:00,3,3,180,"[{""correct"":0,""speed"":26.1},{""correct"":1,""spee...",1000.0,83.33,1048,39,A0001,19520219,M,16,172,,소필영,로아신경과의원,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70007,2022-02-28 17:11:42,2,2,120,"[{""correct"":1,""speed"":13.3},{""correct"":1,""spee...",400.0,100.00,118189,1059,ndb006,19451202,F,6,160,,박정선,남양주백병원,83
70008,2022-02-28 17:13:52,2,2,120,"[{""correct"":1,""speed"":98.5}]",100.0,100.00,118189,1059,ndb006,19451202,F,6,160,,박정선,남양주백병원,83
70009,2022-02-28 17:18:53,2,2,120,"[{""correct"":1,""speed"":9.8},{""correct"":1,""speed...",1000.0,90.91,118190,1059,ndb006,19451202,F,6,160,,박정선,남양주백병원,83
70010,2022-02-28 17:23:42,2,2,120,"[{""correct"":1,""speed"":80.8}]",100.0,100.00,118191,1059,ndb006,19451202,F,6,160,,박정선,남양주백병원,83
70011,2022-02-28 17:25:48,2,2,120,"[{""correct"":1,""speed"":72.5},{""correct"":1,""spee...",200.0,100.00,118191,1059,ndb006,19451202,F,6,160,,박정선,남양주백병원,83

In [24]:
game_log['user_idx'] = game_log['idx']
del game_log['idx']
del game_log['create_time']

In [25]:
game_log.to_csv("game_log_user.csv", encoding='utf8')

In [26]:
np.sum(game_log["game_log_next_level"] == game_log["game_log_level"])

55483

In [37]:
for idx, val in tqdm(game_log.iterrows(), total=game_log.shape[0]):
    game_log['game_log_record'][idx] = eval(val['game_log_record'])

  0%|                                                                                        | 0/64959 [00:00<?, ?it/s]C:\Users\sanghyun\AppData\Local\Temp\ipykernel_12024\1726236212.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  game_log['game_log_record'][idx] = eval(val['game_log_record'])
 70%|████████████████████████████████████████████████████▊                      | 45750/64959 [04:02<01:41, 188.98it/s]

ValueError: cannot set using a list-like indexer with a different length than the value

In [33]:
game_log

,game_log_next_level,game_log_level,game_log_limit,game_log_record,game_log_score,game_log_success,assignment_unit_user,userId,birth,gender,education,height,job,name,organization,organization_idx,user_idx
game_log_idx,,,,,,,,,,,,,,,,,
721,4,4,300,"[{""correct"":1,""speed"":286.9}]",100.0,100.00,1045,A0001,19520219,M,16,172,,소필영,로아신경과의원,4,39
749,3,3,180,"[{""correct"":1,""speed"":25.2},{""correct"":1,""spee...",2000.0,95.24,1046,A0001,19520219,M,16,172,,소필영,로아신경과의원,4,39
768,3,3,180,"[{""correct"":1,""speed"":5.8},{""correct"":1,""speed...",2300.0,95.83,1046,A0001,19520219,M,16,172,,소필영,로아신경과의원,4,39
718,3,3,180,"[{""correct"":1,""speed"":44.7},{""correct"":1,""spee...",400.0,100.00,1048,A0001,19520219,M,16,172,,소필영,로아신경과의원,4,39
719,3,3,180,"[{""correct"":0,""speed"":26.1},{""correct"":1,""spee...",1000.0,83.33,1048,A0001,19520219,M,16,172,,소필영,로아신경과의원,4,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70007,2,2,120,"[{""correct"":1,""speed"":13.3},{""correct"":1,""spee...",400.0,100.00,118189,ndb006,19451202,F,6,160,,박정선,남양주백병원,83,1059
70008,2,2,120,"[{""correct"":1,""speed"":98.5}]",100.0,100.00,118189,ndb006,19451202,F,6,160,,박정선,남양주백병원,83,1059
70009,2,2,120,"[{""correct"":1,""speed"":9.8},{""correct"":1,""speed...",1000.0,90.91,118190,ndb006,19451202,F,6,160,,박정선,남양주백병원,83,1059
70010,2,2,120,"[{""correct"":1,""speed"":80.8}]",100.0,100.00,118191,ndb006,19451202,F,6,160,,박정선,남양주백병원,83,1059
70011,2,2,120,"[{""correct"":1,""speed"":72.5},{""correct"":1,""spee...",200.0,100.00,118191,ndb006,19451202,F,6,160,,박정선,남양주백병원,83,1059

In [15]:
x.type()

AttributeError: 'list' object has no attribute 'type'

In [35]:
game_log['game_log_record'][721].type()

AttributeError: 'str' object has no attribute 'type'